version: '3'

services:
  minio:
    image: bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - storage:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=jahodka123
      - MINIO_DEFAULT_BUCKETS=datasets,reports

volumes:
  storage:

# Lab: MinIO v kompozicii
# image: bitnami/minio
# admin: admin
# password: jahodka123
# default buckets: datasets, reports
# volume: storage:/bitnami/minio/data
